version: '3.7'

services:
  couchdb:
    image: bitnami/couchdb:latest
    environment:
    - COUCHDB_PASSWORD=tachyon
    ports:
    - '1234:1234'
    - '4369:4369'
    - '5984:5984'
    volumes:
    - couchdb_data:/bitnami/couchdb

volumes:
  couchdb_data:
    driver: local
